
CREATE TABLE Zone(
	id INTEGER NOT NULL,
	colore VARCHAR(10) NOT NULL UNIQUE,
	PRIMARY KEY (id)
);

CREATE TABLE Regole(
	id INTEGER NOT NULL AUTO_INCREMENT,
	campo VARCHAR(30) NOT NULL,
	descrizione TEXT NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE Prevede(
	id INTEGER NOT NULL,
	idZona INTEGER NOT NULL,
	idRegola INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (idZona) REFERENCES Zone(id),
	FOREIGN KEY (idRegola) REFERENCES Regole(id)
);

CREATE TABLE Regioni(
	id INTEGER NOT NULL,
	nome VARCHAR(30) NOT NULL UNIQUE,
	colore VARCHAR(10) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (colore) REFERENCES Zone(colore)
);